export const topics = [
  'Clothes and Accessories',
  'Colours',
  'Communications and Technology',
  'Education',
  'Entertainment and Media',
  'Environment',
  'Food and Drink',
  'Health, Medicine and Exercise',
  'Hobbies and Leisure',
  'Home',
  'Language',
  'Personal Feelings, Opinions and Experiences',
  'Places: Buildings',
  'Places: Countryside',
  'Places: Town and City',
  'Services',
  'Shopping',
  'Sport',
  'The Natural World',
  'Time',
  'Travel and Transport',
  'Weather',
  'Work and Jobs'
]

export const wordTypes = [
  '(av & v)',
  '(adj)',
  '(adj & n)',
  '(adj & v)',
  '(adj & adv)',
  '(adj & exclam)',
  '(adj & det)',
  '(adj, n & v)',
  '(adj, adv, det & v)',
  '(adj & adv, n)',
  '(adj, adv & n)',
  '(adj, adv & exclam)',
  '(adj, adv & prep)',
  '(adj, adv & v)',
  '(adj, adv, det & pron)',
  '(adj, exclam & v)',
  '(adj, det & pron)',
  '(adj & n & v)',
  '(adj, n & prep)',
  '(adj, n, prep & adv)',
  '(adj, pron & adv)',
  '(adj, pron & det)',
  '(adj, pron & v)',
  '(adv)',
  '(adv & adj)',
  '(adv & conj)',
  '(adv & n)',
  '(adv & prep)',
  '(adv, adj & n)',
  '(adv, adj & prep)',
  '(adv, det, pron)',
  '(adv, det & n)',
  '(adv, det & pron)',
  '(adv, det, n & pron)',
  '(adv, conj & prep)',
  '(adv, prep & adj)',
  '(conj)',
  '(conj & prep)',
  '(conj, n & v)',
  '(conj, det & pron)',
  '(det)',
  '(det & n)',
  '(det & pron)',
  '(exclam)',
  '(exclam & v)',
  '(phr)',
  '(phr v)',
  '(phr v & adj)',
  '(prep)',
  '(prep & conj)',
  '(prep phr)',
  '(prep, conj)',
  '(prep & adv)',
  '(prep & v)',
  '(prep, adv & conj)',
  '(pron)',
  '(pron & det)',
  '(mv)',
  '(n)',
  '(n pl)',
  '(n & adj)',
  '(n & mv)',
  '(n & v)',
  '(n, adj & adv)',
  '(v)',
  '(v & n)',
  '(v & phr v)'
]
